// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot.proto

#pragma once

#include <cstdint>
#include "lib/error.h"
#include "lib/inline_string.h"
#include "lib/io/io.h"
#include "serialrpc/client.h"
#include "robot.pb_msg.h"

namespace a750pb {
    struct RPCServer;

    struct RPCClient : serialrpc::ClientBase {
        explicit RPCClient();

        explicit RPCClient(std::shared_ptr<lib::io::ReaderWriter> const &conn);

        struct EchoServiceStub {
            static constexpr char ServiceName[] = "EchoService";

            RPCClient& client;

            lib::sync::Mutex mtx;

            explicit EchoServiceStub(RPCClient &client);

            EchoResponse echo(EchoRequest const &req, lib::error err);

            void sleep(SleepRequest const &req, lib::error err);
        } echo_service;

        struct CANServiceStub {
            static constexpr char ServiceName[] = "CANService";

            RPCClient& client;

            lib::sync::Mutex mtx;

            std::function<void(CANFrame const&)> recv_cb;

            explicit CANServiceStub(RPCClient &client);

            void send(CANFrame const &req, lib::error err);

            void subscribe_recv(CANRecvRequest const &req, std::function<void(CANFrame const&)> const &cb, lib::error err);

            void unsubscribe_recv(lib::error err);

            void handle_recv(CANFrame const &msg);
        } can_service;

        struct DebugServiceStub {
            static constexpr char ServiceName[] = "DebugService";

            RPCClient& client;

            lib::sync::Mutex mtx;

            explicit DebugServiceStub(RPCClient &client);

            void memory_write(WriteRequest const &req, lib::error err);

            void reboot(lib::error err);

            void jump(JumpRequest const &req, lib::error err);

            void storage_write(WriteRequest const &req, lib::error err);

            ReadResult memory_read(ReadRequest const &req, lib::error err);

            ReadResult storage_read(ReadRequest const &req, lib::error err);
        } debug_service;

        struct LogServiceStub {
            static constexpr char ServiceName[] = "LogService";

            RPCClient& client;

            lib::sync::Mutex mtx;

            std::function<void(LogItem const&)> recv_cb;

            explicit LogServiceStub(RPCClient &client);

            void subscribe_recv(std::function<void(LogItem const&)> const &cb, lib::error err);

            void unsubscribe_recv(lib::error err);

            void handle_recv(LogItem const &msg);
        } log_service;

        struct RobotServiceStub {
            static constexpr char ServiceName[] = "RobotService";

            RPCClient& client;

            lib::sync::Mutex mtx;

            explicit RobotServiceStub(RPCClient &client);

            RobotState read_state(lib::error err);

            RobotState start_realtime_control(lib::error err);

            RobotState command_joints(CommandJointsRequest const &req, lib::error err);

            void stop_realtime_control(lib::error err);
        } robot_service;

        void handle_event(lib::uint32 event_id, lib::error err) override;
    };
}
