// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot.proto

#include "robot.pb_msg.h"
#include "serialrpc/encoding.h"

using namespace lib;

namespace a750pb {
    void EchoRequest::marshal(EchoRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.NFieldNumber, req.n, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    EchoRequest EchoRequest::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        EchoRequest msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case NFieldNumber:
                msg.n = serialrpc::unmarshal<int32_t>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool EchoRequest::operator==(const EchoRequest& other) const {
        return n == other.n;
    }

    void EchoResponse::marshal(EchoResponse const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.NFieldNumber, req.n, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    EchoResponse EchoResponse::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        EchoResponse msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case NFieldNumber:
                msg.n = serialrpc::unmarshal<int32_t>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool EchoResponse::operator==(const EchoResponse& other) const {
        return n == other.n;
    }

    void SleepRequest::marshal(SleepRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.DurationMsFieldNumber, req.duration_ms, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    SleepRequest SleepRequest::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        SleepRequest msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case DurationMsFieldNumber:
                msg.duration_ms = serialrpc::unmarshal<uint32_t>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool SleepRequest::operator==(const SleepRequest& other) const {
        return duration_ms == other.duration_ms;
    }

    void WriteRequest::marshal(WriteRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.AddressFieldNumber, req.address, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.DataFieldNumber, req.data, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    WriteRequest WriteRequest::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        WriteRequest msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case AddressFieldNumber:
                msg.address = serialrpc::unmarshal<uint64_t>(in, err, nesting-1);
                break;

            case DataFieldNumber:
                msg.data = serialrpc::unmarshal<lib::InlineString<512>>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool WriteRequest::operator==(const WriteRequest& other) const {
        return address == other.address
            && data == other.data;
    }

    void ReadRequest::marshal(ReadRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.AddressFieldNumber, req.address, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.LengthFieldNumber, req.length, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    ReadRequest ReadRequest::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        ReadRequest msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case AddressFieldNumber:
                msg.address = serialrpc::unmarshal<uint64_t>(in, err, nesting-1);
                break;

            case LengthFieldNumber:
                msg.length = serialrpc::unmarshal<uint32_t>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool ReadRequest::operator==(const ReadRequest& other) const {
        return address == other.address
            && length == other.length;
    }

    void ReadResult::marshal(ReadResult const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.DataFieldNumber, req.data, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    ReadResult ReadResult::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        ReadResult msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case DataFieldNumber:
                msg.data = serialrpc::unmarshal<lib::InlineString<512>>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool ReadResult::operator==(const ReadResult& other) const {
        return data == other.data;
    }

    void JumpRequest::marshal(JumpRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.AddressFieldNumber, req.address, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    JumpRequest JumpRequest::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        JumpRequest msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case AddressFieldNumber:
                msg.address = serialrpc::unmarshal<uint64_t>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool JumpRequest::operator==(const JumpRequest& other) const {
        return address == other.address;
    }

    void CANFrame::marshal(CANFrame const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.IdFieldNumber, req.id, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.DataFieldNumber, req.data, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.FdFieldNumber, req.fd, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    CANFrame CANFrame::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        CANFrame msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case IdFieldNumber:
                msg.id = serialrpc::unmarshal<uint32_t>(in, err, nesting-1);
                break;

            case DataFieldNumber:
                msg.data = serialrpc::unmarshal<lib::InlineString<64>>(in, err, nesting-1);
                break;

            case FdFieldNumber:
                msg.fd = serialrpc::unmarshal<bool>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool CANFrame::operator==(const CANFrame& other) const {
        return id == other.id
            && data == other.data
            && fd == other.fd;
    }

    void CANRecvRequest::marshal(CANRecvRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        (void) req;
        (void) out;
        (void) err;
        (void) nesting;
        (void) stack;
    }

    CANRecvRequest CANRecvRequest::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        CANRecvRequest msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool CANRecvRequest::operator==(const CANRecvRequest& other) const {
        (void) other;
        return true;
    }

    void LogItem::marshal(LogItem const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.TextFieldNumber, req.text, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    LogItem LogItem::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        LogItem msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case TextFieldNumber:
                msg.text = serialrpc::unmarshal<lib::InlineString<256>>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool LogItem::operator==(const LogItem& other) const {
        return text == other.text;
    }

    void Joint::marshal(Joint const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.PosRadFieldNumber, req.pos_rad, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.VelRadSFieldNumber, req.vel_rad_s, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.TorqueNmFieldNumber, req.torque_nm, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.TempMosfetCFieldNumber, req.temp_mosfet_c, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.TempRotorCFieldNumber, req.temp_rotor_c, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    Joint Joint::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        Joint msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case PosRadFieldNumber:
                msg.pos_rad = serialrpc::unmarshal<float>(in, err, nesting-1);
                break;

            case VelRadSFieldNumber:
                msg.vel_rad_s = serialrpc::unmarshal<float>(in, err, nesting-1);
                break;

            case TorqueNmFieldNumber:
                msg.torque_nm = serialrpc::unmarshal<float>(in, err, nesting-1);
                break;

            case TempMosfetCFieldNumber:
                msg.temp_mosfet_c = serialrpc::unmarshal<int32_t>(in, err, nesting-1);
                break;

            case TempRotorCFieldNumber:
                msg.temp_rotor_c = serialrpc::unmarshal<int32_t>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool Joint::operator==(const Joint& other) const {
        return pos_rad == other.pos_rad
            && vel_rad_s == other.vel_rad_s
            && torque_nm == other.torque_nm
            && temp_mosfet_c == other.temp_mosfet_c
            && temp_rotor_c == other.temp_rotor_c;
    }

    void RobotState::marshal(RobotState const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.ModeFieldNumber, int32(req.mode), err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.Joint1FieldNumber, req.joint1, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.Joint2FieldNumber, req.joint2, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.Joint3FieldNumber, req.joint3, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.Joint4FieldNumber, req.joint4, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.Joint5FieldNumber, req.joint5, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.Joint6FieldNumber, req.joint6, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    RobotState RobotState::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        RobotState msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case ModeFieldNumber:
                msg.mode = (Mode) serialrpc::unmarshal<int32>(in, err, nesting-1);
                break;

            case Joint1FieldNumber:
                msg.joint1 = serialrpc::unmarshal<Joint>(in, err, nesting-1);
                break;

            case Joint2FieldNumber:
                msg.joint2 = serialrpc::unmarshal<Joint>(in, err, nesting-1);
                break;

            case Joint3FieldNumber:
                msg.joint3 = serialrpc::unmarshal<Joint>(in, err, nesting-1);
                break;

            case Joint4FieldNumber:
                msg.joint4 = serialrpc::unmarshal<Joint>(in, err, nesting-1);
                break;

            case Joint5FieldNumber:
                msg.joint5 = serialrpc::unmarshal<Joint>(in, err, nesting-1);
                break;

            case Joint6FieldNumber:
                msg.joint6 = serialrpc::unmarshal<Joint>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool RobotState::operator==(const RobotState& other) const {
        return mode == other.mode
            && joint1 == other.joint1
            && joint2 == other.joint2
            && joint3 == other.joint3
            && joint4 == other.joint4
            && joint5 == other.joint5
            && joint6 == other.joint6;
    }

    void JointCommand::marshal(JointCommand const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.PosSetpointRadFieldNumber, req.pos_setpoint_rad, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.PosGainNmRadFieldNumber, req.pos_gain_nm_rad, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.VelSetpointRadSFieldNumber, req.vel_setpoint_rad_s, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.VelGainNmsRadFieldNumber, req.vel_gain_nms_rad, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.AccRadSSFieldNumber, req.acc_rad_s_s, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.TorqueNmFieldNumber, req.torque_nm, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    JointCommand JointCommand::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        JointCommand msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case PosSetpointRadFieldNumber:
                msg.pos_setpoint_rad = serialrpc::unmarshal<float>(in, err, nesting-1);
                break;

            case PosGainNmRadFieldNumber:
                msg.pos_gain_nm_rad = serialrpc::unmarshal<float>(in, err, nesting-1);
                break;

            case VelSetpointRadSFieldNumber:
                msg.vel_setpoint_rad_s = serialrpc::unmarshal<float>(in, err, nesting-1);
                break;

            case VelGainNmsRadFieldNumber:
                msg.vel_gain_nms_rad = serialrpc::unmarshal<float>(in, err, nesting-1);
                break;

            case AccRadSSFieldNumber:
                msg.acc_rad_s_s = serialrpc::unmarshal<float>(in, err, nesting-1);
                break;

            case TorqueNmFieldNumber:
                msg.torque_nm = serialrpc::unmarshal<float>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool JointCommand::operator==(const JointCommand& other) const {
        return pos_setpoint_rad == other.pos_setpoint_rad
            && pos_gain_nm_rad == other.pos_gain_nm_rad
            && vel_setpoint_rad_s == other.vel_setpoint_rad_s
            && vel_gain_nms_rad == other.vel_gain_nms_rad
            && acc_rad_s_s == other.acc_rad_s_s
            && torque_nm == other.torque_nm;
    }

    void CommandJointsRequest::marshal(CommandJointsRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.Joint1FieldNumber, req.joint1, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.Joint2FieldNumber, req.joint2, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.Joint3FieldNumber, req.joint3, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.Joint4FieldNumber, req.joint4, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.Joint5FieldNumber, req.joint5, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.Joint6FieldNumber, req.joint6, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    CommandJointsRequest CommandJointsRequest::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        CommandJointsRequest msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case Joint1FieldNumber:
                msg.joint1 = serialrpc::unmarshal<JointCommand>(in, err, nesting-1);
                break;

            case Joint2FieldNumber:
                msg.joint2 = serialrpc::unmarshal<JointCommand>(in, err, nesting-1);
                break;

            case Joint3FieldNumber:
                msg.joint3 = serialrpc::unmarshal<JointCommand>(in, err, nesting-1);
                break;

            case Joint4FieldNumber:
                msg.joint4 = serialrpc::unmarshal<JointCommand>(in, err, nesting-1);
                break;

            case Joint5FieldNumber:
                msg.joint5 = serialrpc::unmarshal<JointCommand>(in, err, nesting-1);
                break;

            case Joint6FieldNumber:
                msg.joint6 = serialrpc::unmarshal<JointCommand>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool CommandJointsRequest::operator==(const CommandJointsRequest& other) const {
        return joint1 == other.joint1
            && joint2 == other.joint2
            && joint3 == other.joint3
            && joint4 == other.joint4
            && joint5 == other.joint5
            && joint6 == other.joint6;
    }





}
