// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot.proto

#include "robot.pb_client.h"
#include "serialrpc/encoding.h"

using namespace lib;

namespace a750pb {
    RPCClient::RPCClient()
        : ClientBase()
        , echo_service(*this)
        , can_service(*this)
        , debug_service(*this)
        , log_service(*this)
    {}

    RPCClient::RPCClient(std::shared_ptr<lib::io::ReaderWriter> const &conn)
        : ClientBase(conn)
        , echo_service(*this)
        , can_service(*this)
        , debug_service(*this)
        , log_service(*this)
    {}

    RPCClient::EchoServiceStub::EchoServiceStub(RPCClient &client)
        : client(client)
    {}

    EchoResponse RPCClient::EchoServiceStub::echo(EchoRequest const &req, lib::error err) {
        return this->client.call<EchoRequest const&, EchoResponse>(1, req, err);
    }

    void RPCClient::EchoServiceStub::sleep(SleepRequest const &req, lib::error err) {
        this->client.call_void<SleepRequest const&>(2, req, err);
    }

    RPCClient::CANServiceStub::CANServiceStub(RPCClient &client)
        : client(client)
    {}

    void RPCClient::CANServiceStub::send(CANFrame const &req, lib::error err) {
        this->client.call_void<CANFrame const&>(3, req, err);
    }

    void RPCClient::CANServiceStub::subscribe_recv(CANRecvRequest const &req, std::function<void(CANFrame const&)> const &cb, lib::error err) {
        {
            sync::Lock lock(this->mtx);
            this->recv_cb = cb;
        }
        this->client.subscribe(4, req, err);
    }

    void RPCClient::CANServiceStub::unsubscribe_recv(lib::error err) {
        sync::Lock lock(this->mtx);
        this->client.unsubscribe(4, err);
        if (err) {
            return;
        }
        this->recv_cb = {};
    }

    void RPCClient::CANServiceStub::handle_recv(CANFrame const &msg) {
        sync::Lock lock(this->mtx);
        if (this->recv_cb) {
            this->recv_cb(msg);
        }
    }

    RPCClient::DebugServiceStub::DebugServiceStub(RPCClient &client)
        : client(client)
    {}

    void RPCClient::DebugServiceStub::memory_write(WriteRequest const &req, lib::error err) {
        this->client.call_void<WriteRequest const&>(5, req, err);
    }

    void RPCClient::DebugServiceStub::reboot(lib::error err) {
        this->client.call_void(6, err);
    }

    void RPCClient::DebugServiceStub::jump(JumpRequest const &req, lib::error err) {
        this->client.call_void<JumpRequest const&>(7, req, err);
    }

    void RPCClient::DebugServiceStub::storage_write(WriteRequest const &req, lib::error err) {
        this->client.call_void<WriteRequest const&>(8, req, err);
    }

    ReadResult RPCClient::DebugServiceStub::memory_read(ReadRequest const &req, lib::error err) {
        return this->client.call<ReadRequest const&, ReadResult>(9, req, err);
    }

    ReadResult RPCClient::DebugServiceStub::storage_read(ReadRequest const &req, lib::error err) {
        return this->client.call<ReadRequest const&, ReadResult>(10, req, err);
    }

    RPCClient::LogServiceStub::LogServiceStub(RPCClient &client)
        : client(client)
    {}

    void RPCClient::LogServiceStub::subscribe_recv(std::function<void(LogItem const&)> const &cb, lib::error err) {
        {
            sync::Lock lock(this->mtx);
            this->recv_cb = cb;
        }
        this->client.subscribe(11, err);
    }

    void RPCClient::LogServiceStub::unsubscribe_recv(lib::error err) {
        sync::Lock lock(this->mtx);
        this->client.unsubscribe(11, err);
        if (err) {
            return;
        }
        this->recv_cb = {};
    }

    void RPCClient::LogServiceStub::handle_recv(LogItem const &msg) {
        sync::Lock lock(this->mtx);
        if (this->recv_cb) {
            this->recv_cb(msg);
        }
    }

    void RPCClient::handle_event(lib::uint32 event_id, lib::error err) {
        switch (event_id) {
        case 1: {
            CANFrame msg = serialrpc::unmarshal<CANFrame>(*this->conn, err);
            if (err) {
                return;
            }
            this->can_service.handle_recv(msg);
            break;
        }
        case 2: {
            LogItem msg = serialrpc::unmarshal<LogItem>(*this->conn, err);
            if (err) {
                return;
            }
            this->log_service.handle_recv(msg);
            break;
        }
        default:
            err("unknown event");
        } // switch
    }
}
