// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot.proto

#pragma once

#include <cstdint>
#include "lib/error.h"
#include "lib/inline_string.h"
#include "lib/io/io.h"
#include "serialrpc/server.h"
#include "robot.pb_msg.h"

namespace a750pb {
    struct RPCServer;

    struct RPCServer : serialrpc::ServerBase {
        explicit RPCServer(EchoService &echo_service, CANService &can_service, DebugService &debug_service, LogService &log_service, RobotService &robot_service);

        void send_CANService_recv(CANFrame const &msg);

        void send_LogService_recv(LogItem const &msg);

        EchoService& echo_service;

        CANService& can_service;

        DebugService& debug_service;

        LogService& log_service;

        RobotService& robot_service;

        void handle_request(lib::uint32 rpc_id, lib::io::ReaderWriter &conn, lib::error err) override;

        void unsubscribe_all() override;
    };
}
