// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot.proto

#pragma once

#include <cstdint>
#include "lib/error.h"
#include "lib/inline_string.h"
#include "lib/io/io.h"
#include "serialrpc/encoding.h"

namespace a750pb {
    struct RPCServer;

    struct EchoRequest {
        static void marshal(EchoRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static EchoRequest unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const EchoRequest& other) const;

        int32_t n = {};

        static const uint32_t NFieldNumber = 1;
    };

    struct EchoResponse {
        static void marshal(EchoResponse const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static EchoResponse unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const EchoResponse& other) const;

        int32_t n = {};

        static const uint32_t NFieldNumber = 1;
    };

    struct SleepRequest {
        static void marshal(SleepRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static SleepRequest unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const SleepRequest& other) const;

        uint32_t duration_ms = {};

        static const uint32_t DurationMsFieldNumber = 1;
    };

    struct WriteRequest {
        static void marshal(WriteRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static WriteRequest unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const WriteRequest& other) const;

        uint64_t address = {};

        lib::InlineString<512> data = {};

        static const uint32_t AddressFieldNumber = 1;

        static const uint32_t DataFieldNumber = 2;
    };

    struct ReadRequest {
        static void marshal(ReadRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static ReadRequest unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const ReadRequest& other) const;

        uint64_t address = {};

        uint32_t length = {};

        static const uint32_t AddressFieldNumber = 1;

        static const uint32_t LengthFieldNumber = 2;
    };

    struct ReadResult {
        static void marshal(ReadResult const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static ReadResult unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const ReadResult& other) const;

        lib::InlineString<512> data = {};

        static const uint32_t DataFieldNumber = 2;
    };

    struct JumpRequest {
        static void marshal(JumpRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static JumpRequest unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const JumpRequest& other) const;

        uint64_t address = {};

        static const uint32_t AddressFieldNumber = 1;
    };

    struct CANFrame {
        static void marshal(CANFrame const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static CANFrame unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const CANFrame& other) const;

        uint32_t id = {};

        lib::InlineString<64> data = {};

        bool fd = {};

        static const uint32_t IdFieldNumber = 1;

        static const uint32_t DataFieldNumber = 2;

        static const uint32_t FdFieldNumber = 3;
    };

    struct CANRecvRequest {
        static void marshal(CANRecvRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static CANRecvRequest unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const CANRecvRequest& other) const;
    };

    struct LogItem {
        static void marshal(LogItem const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static LogItem unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const LogItem& other) const;

        lib::str text = {};

        static const uint32_t TextFieldNumber = 1;
    };

    struct Joint {
        static void marshal(Joint const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static Joint unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const Joint& other) const;

        float pos_rad = {};

        float vel_rad_s = {};

        float torque_rad_s = {};

        int32_t temp_mosfet_c = {};

        int32_t temp_rotor_c = {};

        static const uint32_t PosRadFieldNumber = 1;

        static const uint32_t VelRadSFieldNumber = 2;

        static const uint32_t TorqueRadSFieldNumber = 3;

        static const uint32_t TempMosfetCFieldNumber = 4;

        static const uint32_t TempRotorCFieldNumber = 5;
    };

    struct RobotState {
        enum Mode {
            Startup = 0,
            Enabled = 1,
            Stopped = 2,
            Fault = 3
        };

        static void marshal(RobotState const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static RobotState unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const RobotState& other) const;

        Mode mode = {};

        Joint joint1 = {};

        Joint joint2 = {};

        Joint joint3 = {};

        Joint joint4 = {};

        Joint joint5 = {};

        Joint joint6 = {};

        static const uint32_t ModeFieldNumber = 1;

        static const uint32_t Joint1FieldNumber = 2;

        static const uint32_t Joint2FieldNumber = 3;

        static const uint32_t Joint3FieldNumber = 4;

        static const uint32_t Joint4FieldNumber = 5;

        static const uint32_t Joint5FieldNumber = 6;

        static const uint32_t Joint6FieldNumber = 7;
    };

    struct JointCommand {
        static void marshal(JointCommand const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static JointCommand unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const JointCommand& other) const;

        float pos_setpoint_rad = {};

        float pos_gain_nm_rad = {};

        float vel_setpoint_rad_s = {};

        float vel_gain_nms_rad = {};

        float torque_nm = {};

        static const uint32_t PosSetpointRadFieldNumber = 1;

        static const uint32_t PosGainNmRadFieldNumber = 2;

        static const uint32_t VelSetpointRadSFieldNumber = 3;

        static const uint32_t VelGainNmsRadFieldNumber = 4;

        static const uint32_t TorqueNmFieldNumber = 5;
    };

    struct CommandJointsRequest {
        static void marshal(CommandJointsRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static CommandJointsRequest unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const CommandJointsRequest& other) const;

        JointCommand joint1 = {};

        JointCommand joint2 = {};

        JointCommand joint3 = {};

        JointCommand joint4 = {};

        JointCommand joint5 = {};

        JointCommand joint6 = {};

        static const uint32_t Joint1FieldNumber = 1;

        static const uint32_t Joint2FieldNumber = 2;

        static const uint32_t Joint3FieldNumber = 3;

        static const uint32_t Joint4FieldNumber = 4;

        static const uint32_t Joint5FieldNumber = 5;

        static const uint32_t Joint6FieldNumber = 6;
    };

    struct EchoService {
        virtual EchoResponse echo(EchoRequest const &req, lib::error err) = 0;

        virtual void sleep(SleepRequest const &req, lib::error err) = 0;
    };

    struct DebugService {
        virtual void memory_write(WriteRequest const &req, lib::error err) = 0;

        virtual ReadResult memory_read(ReadRequest const &req, lib::error err) = 0;

        virtual void storage_write(WriteRequest const &req, lib::error err) = 0;

        virtual ReadResult storage_read(ReadRequest const &req, lib::error err) = 0;

        virtual void reboot(lib::error err) = 0;

        virtual void jump(JumpRequest const &req, lib::error err) = 0;
    };

    struct CANService {
        virtual void send(CANFrame const &req, lib::error err) = 0;

        virtual void subscribe_recv(RPCServer &server, CANRecvRequest const &req, lib::error err) = 0;

        virtual void unsubscribe_recv() = 0;
    };

    struct LogService {
        virtual void subscribe_recv(RPCServer &server, lib::error err) = 0;

        virtual void unsubscribe_recv() = 0;
    };

    struct RobotService {
        virtual RobotState read_state(lib::error err) = 0;

        virtual RobotState start_realtime_control(lib::error err) = 0;

        virtual void stop_realtime_control(lib::error err) = 0;

        virtual RobotState command_joints(CommandJointsRequest const &req, lib::error err) = 0;
    };
}
