// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot.proto

#pragma once

#include <cstdint>
#include "lib/error.h"
#include "lib/inline_string.h"
#include "lib/io/io.h"
#include "serialrpc/encoding.h"

namespace a750pb {
    struct RPCServer;

    struct EchoRequest {
        static void marshal(EchoRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static EchoRequest unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const EchoRequest& other) const;

        int32_t n = {};

        static const uint32_t NFieldNumber = 1;
    };

    struct EchoResponse {
        static void marshal(EchoResponse const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static EchoResponse unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const EchoResponse& other) const;

        int32_t n = {};

        static const uint32_t NFieldNumber = 1;
    };

    struct SleepRequest {
        static void marshal(SleepRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static SleepRequest unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const SleepRequest& other) const;

        uint32_t duration_ms = {};

        static const uint32_t DurationMsFieldNumber = 1;
    };

    struct WriteRequest {
        static void marshal(WriteRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static WriteRequest unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const WriteRequest& other) const;

        uint64_t address = {};

        lib::InlineString<512> data = {};

        static const uint32_t AddressFieldNumber = 1;

        static const uint32_t DataFieldNumber = 2;
    };

    struct ReadRequest {
        static void marshal(ReadRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static ReadRequest unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const ReadRequest& other) const;

        uint64_t address = {};

        uint32_t length = {};

        static const uint32_t AddressFieldNumber = 1;

        static const uint32_t LengthFieldNumber = 2;
    };

    struct ReadResult {
        static void marshal(ReadResult const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static ReadResult unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const ReadResult& other) const;

        lib::InlineString<512> data = {};

        static const uint32_t DataFieldNumber = 2;
    };

    struct JumpRequest {
        static void marshal(JumpRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static JumpRequest unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const JumpRequest& other) const;

        uint64_t address = {};

        static const uint32_t AddressFieldNumber = 1;
    };

    struct CANFrame {
        static void marshal(CANFrame const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static CANFrame unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const CANFrame& other) const;

        uint32_t id = {};

        lib::InlineString<64> data = {};

        bool fd = {};

        static const uint32_t IdFieldNumber = 1;

        static const uint32_t DataFieldNumber = 2;

        static const uint32_t FdFieldNumber = 3;
    };

    struct CANRecvRequest {
        static void marshal(CANRecvRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static CANRecvRequest unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const CANRecvRequest& other) const;
    };

    struct LogItem {
        static void marshal(LogItem const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack);

        static LogItem unmarshal(lib::io::Reader &in, lib::error err, int nesting = 128);

        bool operator==(const LogItem& other) const;

        lib::str text = {};

        static const uint32_t TextFieldNumber = 1;
    };

    struct EchoService {
        virtual EchoResponse echo(EchoRequest const &req, lib::error err) = 0;

        virtual void sleep(SleepRequest const &req, lib::error err) = 0;
    };

    struct DebugService {
        virtual void memory_write(WriteRequest const &req, lib::error err) = 0;

        virtual ReadResult memory_read(ReadRequest const &req, lib::error err) = 0;

        virtual void storage_write(WriteRequest const &req, lib::error err) = 0;

        virtual ReadResult storage_read(ReadRequest const &req, lib::error err) = 0;

        virtual void reboot(lib::error err) = 0;

        virtual void jump(JumpRequest const &req, lib::error err) = 0;
    };

    struct CANService {
        virtual void send(CANFrame const &req, lib::error err) = 0;

        virtual void subscribe_recv(RPCServer &server, CANRecvRequest const &req, lib::error err) = 0;

        virtual void unsubscribe_recv() = 0;
    };

    struct LogService {
        virtual void subscribe_recv(RPCServer &server, lib::error err) = 0;

        virtual void unsubscribe_recv() = 0;
    };
}
