// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot.proto

#include "robot.pb_msg.h"
#include "serialrpc/encoding.h"

using namespace lib;

namespace a750pb {
    void EchoRequest::marshal(EchoRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.NFieldNumber, req.n, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    EchoRequest EchoRequest::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        EchoRequest msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case NFieldNumber:
                msg.n = serialrpc::unmarshal<int32_t>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool EchoRequest::operator==(const EchoRequest& other) const {
        return n == other.n;
    }

    void EchoResponse::marshal(EchoResponse const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.NFieldNumber, req.n, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    EchoResponse EchoResponse::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        EchoResponse msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case NFieldNumber:
                msg.n = serialrpc::unmarshal<int32_t>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool EchoResponse::operator==(const EchoResponse& other) const {
        return n == other.n;
    }

    void SleepRequest::marshal(SleepRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.DurationMsFieldNumber, req.duration_ms, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    SleepRequest SleepRequest::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        SleepRequest msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case DurationMsFieldNumber:
                msg.duration_ms = serialrpc::unmarshal<uint32_t>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool SleepRequest::operator==(const SleepRequest& other) const {
        return duration_ms == other.duration_ms;
    }

    void WriteRequest::marshal(WriteRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.AddressFieldNumber, req.address, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.DataFieldNumber, req.data, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    WriteRequest WriteRequest::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        WriteRequest msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case AddressFieldNumber:
                msg.address = serialrpc::unmarshal<uint64_t>(in, err, nesting-1);
                break;

            case DataFieldNumber:
                msg.data = serialrpc::unmarshal<lib::InlineString<512>>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool WriteRequest::operator==(const WriteRequest& other) const {
        return address == other.address
            && data == other.data;
    }

    void ReadRequest::marshal(ReadRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.AddressFieldNumber, req.address, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.LengthFieldNumber, req.length, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    ReadRequest ReadRequest::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        ReadRequest msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case AddressFieldNumber:
                msg.address = serialrpc::unmarshal<uint64_t>(in, err, nesting-1);
                break;

            case LengthFieldNumber:
                msg.length = serialrpc::unmarshal<uint32_t>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool ReadRequest::operator==(const ReadRequest& other) const {
        return address == other.address
            && length == other.length;
    }

    void ReadResult::marshal(ReadResult const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.DataFieldNumber, req.data, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    ReadResult ReadResult::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        ReadResult msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case DataFieldNumber:
                msg.data = serialrpc::unmarshal<lib::InlineString<512>>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool ReadResult::operator==(const ReadResult& other) const {
        return data == other.data;
    }

    void JumpRequest::marshal(JumpRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.AddressFieldNumber, req.address, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    JumpRequest JumpRequest::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        JumpRequest msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case AddressFieldNumber:
                msg.address = serialrpc::unmarshal<uint64_t>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool JumpRequest::operator==(const JumpRequest& other) const {
        return address == other.address;
    }

    void CANFrame::marshal(CANFrame const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.IdFieldNumber, req.id, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.DataFieldNumber, req.data, err, nesting-1, stack);
        if (err) {
            return;
        }
        serialrpc::marshal_field(out, req.FdFieldNumber, req.fd, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    CANFrame CANFrame::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        CANFrame msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case IdFieldNumber:
                msg.id = serialrpc::unmarshal<uint32_t>(in, err, nesting-1);
                break;

            case DataFieldNumber:
                msg.data = serialrpc::unmarshal<lib::InlineString<64>>(in, err, nesting-1);
                break;

            case FdFieldNumber:
                msg.fd = serialrpc::unmarshal<bool>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool CANFrame::operator==(const CANFrame& other) const {
        return id == other.id
            && data == other.data
            && fd == other.fd;
    }

    void CANRecvRequest::marshal(CANRecvRequest const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        (void) req;
        (void) out;
        (void) err;
        (void) nesting;
        (void) stack;
    }

    CANRecvRequest CANRecvRequest::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        CANRecvRequest msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool CANRecvRequest::operator==(const CANRecvRequest& other) const {
        (void) other;
        return true;
    }

    void LogItem::marshal(LogItem const &req, lib::io::Writer &out, lib::error err, int nesting, serialrpc::Stack &stack) {
        serialrpc::marshal_field(out, req.TextFieldNumber, req.text, err, nesting-1, stack);
        if (err) {
            return;
        }
    }

    LogItem LogItem::unmarshal(lib::io::Reader &in, lib::error err, int nesting) {
        LogItem msg;

        for (;;) {
            serialrpc::Tag tag = serialrpc::read_tag(in, err);
            if (err) {
                return msg;
            }

            if (tag.type == serialrpc::Tag::End) {
                return msg;
            }

            switch (tag.field_num) {
            case TextFieldNumber:
                msg.text = serialrpc::unmarshal<lib::str>(in, err, nesting-1);
                break;

            default:
                serialrpc::skip(in, tag.type, err, nesting-1);
                if (err) {
                    return msg;
                }
            }
        }

        return msg;
    }

    bool LogItem::operator==(const LogItem& other) const {
        return text == other.text;
    }




}
