// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot.proto

#include "robot.pb_server.h"
#include "serialrpc/encoding.h"

using namespace lib;

namespace a750pb {
    RPCServer::RPCServer(EchoService &echo_service, CANService &can_service, DebugService &debug_service, LogService &log_service, RobotService &robot_service)
        : echo_service(echo_service)
        , can_service(can_service)
        , debug_service(debug_service)
        , log_service(log_service)
        , robot_service(robot_service)
    {}

    void RPCServer::send_CANService_recv(CANFrame const &msg) {
        this->send_event(1, msg);
    }

    void RPCServer::send_LogService_recv(LogItem const &msg) {
        this->send_event(2, msg);
    }

    void RPCServer::handle_request(lib::uint32 rpc_id, lib::io::ReaderWriter &conn, lib::error err) {
        switch (rpc_id) {
        case 1: {
            EchoRequest msg = serialrpc::unmarshal<EchoRequest>(conn, err);
            if (err) {
                return;
            }
            RPCServer::ServerErrorHandler handler_err(*this, err);
            EchoResponse resp = echo_service.echo(msg, handler_err);
            if (err || handler_err) {
                return;
            }
            send_reply_msg(conn, resp, err);
            if (err) {
                return;
            }
            break;
        }
        case 2: {
            SleepRequest msg = serialrpc::unmarshal<SleepRequest>(conn, err);
            if (err) {
                return;
            }
            echo_service.sleep(msg, RPCServer::ServerErrorHandler(*this, err));
            if (err) {
                return;
            }
            send_reply_void(conn, err);
            if (err) {
                return;
            }
            break;
        }
        case 3: {
            CANFrame msg = serialrpc::unmarshal<CANFrame>(conn, err);
            if (err) {
                return;
            }
            can_service.send(msg, RPCServer::ServerErrorHandler(*this, err));
            if (err) {
                return;
            }
            send_reply_void(conn, err);
            if (err) {
                return;
            }
            break;
        }
        case 4: {
            bool enabled = conn.read_byte(err);
            if (err) {
                return;
            }
            if (enabled) {
                CANRecvRequest msg = serialrpc::unmarshal<CANRecvRequest>(conn, err);
                if (err) {
                    return;
                }
                RPCServer::ServerErrorHandler handler_err(*this, err);
                can_service.subscribe_recv(*this, msg, handler_err);
                if (err || handler_err) {
                    return;
                }
            } else {
                can_service.unsubscribe_recv();
            }
            send_code(conn, serialrpc::Reply, err);
            if (err) {
                return;
            }
            break;
        }
        case 5: {
            WriteRequest msg = serialrpc::unmarshal<WriteRequest>(conn, err);
            if (err) {
                return;
            }
            debug_service.memory_write(msg, RPCServer::ServerErrorHandler(*this, err));
            if (err) {
                return;
            }
            send_reply_void(conn, err);
            if (err) {
                return;
            }
            break;
        }
        case 6: {
            serialrpc::skip(conn, err);
            if (err) {
                return;
            }
            debug_service.reboot(RPCServer::ServerErrorHandler(*this, err));
            if (err) {
                return;
            }
            send_reply_void(conn, err);
            if (err) {
                return;
            }
            break;
        }
        case 7: {
            JumpRequest msg = serialrpc::unmarshal<JumpRequest>(conn, err);
            if (err) {
                return;
            }
            debug_service.jump(msg, RPCServer::ServerErrorHandler(*this, err));
            if (err) {
                return;
            }
            send_reply_void(conn, err);
            if (err) {
                return;
            }
            break;
        }
        case 8: {
            WriteRequest msg = serialrpc::unmarshal<WriteRequest>(conn, err);
            if (err) {
                return;
            }
            debug_service.storage_write(msg, RPCServer::ServerErrorHandler(*this, err));
            if (err) {
                return;
            }
            send_reply_void(conn, err);
            if (err) {
                return;
            }
            break;
        }
        case 9: {
            ReadRequest msg = serialrpc::unmarshal<ReadRequest>(conn, err);
            if (err) {
                return;
            }
            RPCServer::ServerErrorHandler handler_err(*this, err);
            ReadResult resp = debug_service.memory_read(msg, handler_err);
            if (err || handler_err) {
                return;
            }
            send_reply_msg(conn, resp, err);
            if (err) {
                return;
            }
            break;
        }
        case 10: {
            ReadRequest msg = serialrpc::unmarshal<ReadRequest>(conn, err);
            if (err) {
                return;
            }
            RPCServer::ServerErrorHandler handler_err(*this, err);
            ReadResult resp = debug_service.storage_read(msg, handler_err);
            if (err || handler_err) {
                return;
            }
            send_reply_msg(conn, resp, err);
            if (err) {
                return;
            }
            break;
        }
        case 11: {
            bool enabled = conn.read_byte(err);
            if (err) {
                return;
            }
            if (enabled) {
                serialrpc::skip(conn, err);
                if (err) {
                    return;
                }
                RPCServer::ServerErrorHandler handler_err(*this, err);
                log_service.subscribe_recv(*this, handler_err);
                if (err || handler_err) {
                    return;
                }
            } else {
                log_service.unsubscribe_recv();
            }
            send_code(conn, serialrpc::Reply, err);
            if (err) {
                return;
            }
            break;
        }
        case 12: {
            serialrpc::skip(conn, err);
            if (err) {
                return;
            }
            RPCServer::ServerErrorHandler handler_err(*this, err);
            RobotState resp = robot_service.read_state(handler_err);
            if (err || handler_err) {
                return;
            }
            send_reply_msg(conn, resp, err);
            if (err) {
                return;
            }
            break;
        }
        case 13: {
            serialrpc::skip(conn, err);
            if (err) {
                return;
            }
            RPCServer::ServerErrorHandler handler_err(*this, err);
            RobotState resp = robot_service.start_realtime_control(handler_err);
            if (err || handler_err) {
                return;
            }
            send_reply_msg(conn, resp, err);
            if (err) {
                return;
            }
            break;
        }
        case 14: {
            CommandJointsRequest msg = serialrpc::unmarshal<CommandJointsRequest>(conn, err);
            if (err) {
                return;
            }
            RPCServer::ServerErrorHandler handler_err(*this, err);
            RobotState resp = robot_service.command_joints(msg, handler_err);
            if (err || handler_err) {
                return;
            }
            send_reply_msg(conn, resp, err);
            if (err) {
                return;
            }
            break;
        }
        case 15: {
            serialrpc::skip(conn, err);
            if (err) {
                return;
            }
            robot_service.stop_realtime_control(RPCServer::ServerErrorHandler(*this, err));
            if (err) {
                return;
            }
            send_reply_void(conn, err);
            if (err) {
                return;
            }
            break;
        }
        default:
            send_code(conn, serialrpc::Unknown, err);
        } // switch
    }

    void RPCServer::unsubscribe_all() {
        this->can_service.unsubscribe_recv();
        this->log_service.unsubscribe_recv();
    }
}
